name: Build and Deploy

on:
    push:
      branches:
        - main
        - '**' # Allow all branches, for testing purposes

    workflow_dispatch: # Allow manual triggers

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Define the environment name so we can get the settings from GitHub
    environment: Tailgunner Production

    defaults:
      run:
        working-directory: ./src

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Shallow clone for faster checkout

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, pdo, bcmath, json, xml, zip
          coverage: none

      - name: Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader --prefer-dist

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

          # Specifies non-default lock file location
          cache-dependency-path: './src/package-lock.json'

      - name: Install NPM Dependencies & Build Assets
        env:
          NODE_ENV: production
        working-directory: ./src
        run: |
          npm ci
          node node_modules/vite/bin/vite.js build

      - name: Create Deployment Package
        run: |
          TIMESTAMP="$(date +%Y-%m-%d-%H-%M-%S)"
          cd ..
          tar -czf "deploy-${TIMESTAMP}.tar.gz" \
            --exclude='node_modules' \
            --exclude='.git*' \
            --exclude='tests' \
            --exclude='storage/logs/*' \
            --exclude='storage/framework/cache/*' \
            --exclude='storage/framework/sessions/*' \
            --exclude='.env*' \
            --exclude='phpunit.xml' \
            src/
          mv "deploy-${TIMESTAMP}.tar.gz" src/

      - name: Copy deployment package and script
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "src/deploy-*.tar.gz,.github/workflows/deploy-to-prod.sh"
          target: "~/deployments/"
          strip_components: 1
          overwrite: true

      - name: Unpack and finalize
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            chmod +x ~/deployments/workflows/deploy-to-prod.sh
            ~/deployments/workflows/deploy-to-prod.sh
