name: Build and Deploy

on:
    push:
      branches:
        - main
        - '**'
    workflow_dispatch:  # Allow manual triggers

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./

    steps:
      - name: Create Test File
        run: |
          touch test_12.txt

      - name: Copy deployment package
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "test_12.txt"
          target: "~/public_html"
          strip_components: 1
          debug: true
