name: Build and Deploy

on:
    push:
      branches:
        - main
        - '**'
    workflow_dispatch:  # Allow manual triggers

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Tailgunner Production

    defaults:
      run:
        working-directory: ./src

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, pdo, bcmath, json, xml, zip
          coverage: none

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './src/package-lock.json'

      - name: Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader --prefer-dist

      - name: Install NPM Dependencies & Build Assets
        env:
          VITE_APP_URL: https://tailgunner.app
          NODE_ENV: production
        working-directory: ./src
        run: |
          # Debug env vars

          echo "Environment variables:"
          echo "VITE_APP_URL=$VITE_APP_URL"
          echo "NODE_ENV=$NODE_ENV"

          # Create temp debug config
          echo "  VITE_APP_URL: $VITE_APP_URL," >> vite.config.debug.js
          echo "  NODE_ENV: $NODE_ENV" >> vite.config.debug.js

          rm -rf node_modules package-lock.json
          npm install
          node node_modules/vite/bin/vite.js build

      - name: Create Deployment Package
        run: |
          TIMESTAMP="$(date +%Y-%m-%d-%H-%M-%S)"
          cd ..
          tar -czf "deploy-${TIMESTAMP}.tar.gz" \
            --exclude='node_modules' \
            --exclude='.git*' \
            --exclude='tests' \
            --exclude='storage/logs/*' \
            --exclude='storage/framework/cache/*' \
            --exclude='storage/framework/sessions/*' \
            src/
          mv "deploy-${TIMESTAMP}.tar.gz" src/

      - name: Copy deployment package
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "src/deploy-*.tar.gz"
          target: "~/deployments/"
          strip_components: 1

      - name: Unpack and finalize
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            DEPLOY_PATH=~/deployments
            TARBALL="$(ls -1t ${DEPLOY_PATH}/deploy-*.tar.gz | head -n1)"
            TIMESTAMP="$(basename "$TARBALL" | sed -E 's/.*deploy-(.+)\.tar\.gz/\1/g')"
            RELEASE_PATH=~/deployments/releases/${TIMESTAMP}
            mkdir -p ${RELEASE_PATH}
            tar -xzf "$TARBALL" -C ${RELEASE_PATH}

            ln -s ~/shared/storage ${RELEASE_PATH}/src/storage
            ln -s ~/shared/.env ${RELEASE_PATH}/src/.env
